cask "font-kyobo-handwriting-2022-khn" do
  version "1.010,20230227"
  sha256 "506320861fae6d16286fbceb8f0f48b254e89f3abf66ba5d52040b433c53b9f1"

  url "https://store.kyobobook.co.kr/api/s3/download/hwrt-handwritingFont-font?fileName=KyoboHandwriting2022khn.ttf"
  name "Kyobo Handwriting 2022 khn"
  name "교보 손글씨 2022 김혜남"
  homepage "https://store.kyobobook.co.kr/handwriting/font"

  font "KyoboHandwriting2022khn.ttf"

  caveats do
    # license "#{homepage}"
    license "https://store.kyobobook.co.kr/handwriting/font"
    <<~EOS
      You can preview font information generated by `otfinfo` at:
        #{__dir__}/#{token}.otfinfo
    EOS
  end
end
