cask "font-kyobo-handwriting-2019" do
  version "1.000,20200217"
  sha256 "92ed8baae0b00321994560281650f7a6ade89dcef6f8848fa511391720ce9aa5"

  url "https://store.kyobobook.co.kr/api/s3/download/hwrt-handwritingFont-font?fileName=KyoboHandwriting2019.ttf"
  name "Kyobo Handwriting 2019"
  name "교보 손글씨 2019"
  homepage "https://store.kyobobook.co.kr/handwriting/font"

  font "KyoboHandwriting2019.ttf"

  caveats do
    # license "#{homepage}"
    license "https://store.kyobobook.co.kr/handwriting/font"
    <<~EOS
      You can preview font information generated by `otfinfo` at:
        #{__dir__}/#{token}.otfinfo
    EOS
  end
end
