cask "font-kyobo-handwriting-2020-pdy" do
  version "1.000,20210106"
  sha256 "b144bc49d528d35cde32c17ccd6fc785ca819d4081ceaac9433ee6e2bf1c5ea1"

  url "https://store.kyobobook.co.kr/api/s3/download/hwrt-handwritingFont-font?fileName=KyoboHandwriting2020pdy.ttf"
  name "Kyobo Handwriting 2020 pdy"
  name "교보 손글씨 2020 박도연"
  homepage "https://store.kyobobook.co.kr/handwriting/font"

  font "KyoboHandwriting2020pdy.ttf"

  caveats do
    # license "#{homepage}"
    license "https://store.kyobobook.co.kr/handwriting/font"
    <<~EOS
      You can preview font information generated by `otfinfo` at:
        #{__dir__}/#{token}.otfinfo
    EOS
  end
end
